website/views.py
#this page creates the necessary routes
from flask import Blueprint, render_template, flash, request, redirect, url_for
from flask_login import login_required, current_user
from .models import Post, User
from . import db


views = Blueprint("views", __name__)

#automatically route to the home page when the user logs in
@views.route("/")
@views.route("/home")
@login_required
def home():
    #on the home page, display all posts.
    posts = Post.query.filter_by(is_private=0)
    return render_template("home.html", user=current_user, posts=posts)



#HTTP request for creating a post
@views.route("/create-post", methods=['GET', 'POST'])
@login_required
def create_post():
    if request.method == "POST":
        #get values from the form
        title = request.form.get('title')
        text = request.form.get('text')
        tag1 = request.form.get('tag1')
        tag2 = request.form.get('tag2')
        tag3 = request.form.get('tag3')
        isprivate = request.form.get("is_private")
        
        #if values are empty, flash an error message
        if not title or not text or not tag1 or not tag2 or not tag3:
            flash('Posts and tags cannot be empty', category='error')
        else:
            #check the private/public checkbox values
            if isprivate:
                isprivate = 1
            else:
                isprivate = 0
            #create a post with the entered title, text, tags, and update the author and privacy of the post
            post = Post(title=title, text=text, tag1=tag1, tag2=tag2, tag3=tag3, author=current_user.id, is_private=isprivate)
            db.session.add(post)
            db.session.commit()
            #flash a message showing that post has been created, and redirect to the home page.
            flash('Post created!', category='success')
            return redirect(url_for('views.home'))
    #if there is an issue when creating the post, render the create post page.
    return render_template('create_post.html', user=current_user)



#HTTP request for deleting a post
@views.route("/delete-post/<id>")
@login_required
def delete_post(id):
    #query for the first post that has the id of the post to be deleted
    post = Post.query.filter_by(id=id).first()
    if not post:
        flash("Post does not exist", category='error')
    elif current_user.id != post.author:
        flash('You do not have permission to delete this post', category='error')
    else:
        #if the post exists and the current logged in user is the author of the post, delete the post, commit changes,
        #and add a flashed message to reflect this
        db.session.delete(post)
        db.session.commit()
        flash('Post deleted.', category='success')
    #no matter what, render the home screen after deletion
    return redirect(url_for('views.home'))



#HTTP request for updating a post
@views.route("/update-post/<id>", methods=['GET', 'POST'])
@login_required
def update_post(id):
    #query for the first post that has the id of the post to be updated
    post = Post.query.filter_by(id=id).first()
    if not post:
        flash("Post does not exist.", category='error')
    elif current_user.id != post.author:
        flash('You do not have permission to edit this post.', category='error')
    elif request.method == "POST":
        #if the post exists and the current logged in user is the author, 
        #check to see if the form values are empty
        if not request.form['title'] or not request.form['text'] or not request.form['tag1'] or not request.form['tag2'] or not request.form['tag3']:
            flash('Posts and tags cannot be empty', category='error')
        else:
            #otherwise, update the database table with the new updated values
            post.title = request.form['title']
            post.text = request.form['text']
            post.tag1 = request.form['tag1']
            post.tag2 = request.form['tag2']
            post.tag3 = request.form['tag3']
            #update privacy
            if request.form.get('is_private'):
                post.is_private = 1
            else:
                post.is_private = 0
            db.session.commit()
            #commit changes and redirect to home page
            return redirect(url_for('views.home'))
    #if it fails, render the same update post screen with an error message
    return render_template('update_post.html', post=post, user=current_user)


#HTTP request for viewing a user's posts
@views.route("/posts/<username>")
@login_required
def posts(username):
    #query the database and find the first user with the username that is to be viewed
    user = User.query.filter_by(username=username).first()

    #if user does not exist, flash error message and redirect to home
    if not user:
        flash('No user with that username exists.', category='error')
        return redirect(url_for('views.home'))

    #query the database and find all posts by the user, based on id
    posts = Post.query.filter_by(author=user.id, is_private=0).all()

    #render the post display screen, with posts = to the queried posts and username of the user to be viewed
    return render_template("posts.html", user=current_user, posts=posts, username=username)



#HTTP request for viewing all posts with the tags equal to tag1
@views.route("/tag1/<tag1>")
@login_required
def tag1_posts(tag1):
    #query for all posts with matching tags to tag1 and display them in posts.html
    posts = Post.query.filter_by(tag1=tag1, is_private=0).all() + Post.query.filter_by(tag2=tag1, is_private=0).all() + Post.query.filter_by(tag3=tag1, is_private=0).all()
    return render_template("posts.html", user=current_user, posts=posts, username=tag1)


#HTTP request for viewing all posts with the tags equal to tag2
@views.route("/tag2/<tag2>")
@login_required
def tag2_posts(tag2):
    #query for all posts with matching tags to tag1 and display them in posts.html
    posts = Post.query.filter_by(tag1=tag2, is_private=0).all() + Post.query.filter_by(tag2=tag2, is_private=0).all() + Post.query.filter_by(tag3=tag2, is_private=0).all()
    return render_template("posts.html", user=current_user, posts=posts, username=tag2)


#HTTP request for viewing all posts with the tags equal to tag3
@views.route("/tag3/<tag3>")
@login_required
def tag3_posts(tag3):
    #query for all posts with matching tags to tag1 and display them in posts.html
    posts = Post.query.filter_by(tag1=tag3, is_private=0).all() + Post.query.filter_by(tag2=tag3, is_private=0).all() + Post.query.filter_by(tag3=tag3, is_private=0).all()
    return render_template("posts.html", user=current_user, posts=posts, username=tag3)


#HTTP request for viewing your private posts
@views.route("<username>/private-posts")
@login_required
def private_posts(username):
    #query the database and find the first user with the username to view
    user = User.query.filter_by(username=username).first()

    if not user:
        flash('no user with that username exists', category='error')
        return redirect(url_for('views.home'))
    
    #query all posts by the user that are private, based on id
    posts = Post.query.filter_by(author=user.id, is_private = 1).all()

    #if there are private posts, render them in posts.html
    if posts:
        return render_template("posts.html", user=current_user, posts=posts, username=username)

    #otherwise, flash that there are no private posts and return to home.html
    else:
        flash('You have no private posts.')
        return render_template("home.html", user=current_user, username=username, posts = Post.query.all())

website/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='base-style.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='views.css') }}"
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>{% block title %}{% endblock %}</title>
</head>

<body>
    <nav class="navbar navbar-expand-lg bg-body-tertiary navbar-light navbar-custom">
        <div class="container-fluid">
          <a class="navbar-brand">Navbar</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse">
            <div class="navbar-nav">
              <a class="nav-link active" aria-current="page" href="/home">Home</a>
              {%if user.is_authenticated%}
              
              <a class="nav-link" href="/create-post">Create Post</a>
              <a class="nav-link" href="/{{ current_user.username }}/private-posts">My Private Posts</a>
              <a class="nav-link" href="/logout">Logout</a> 
              {%else%}
              <a class="nav-link" href="/login">Login</a>
              <a class="nav-link" href="/sign-up">Signup</a>
              {%endif%}
            </div>
          </div>
        </div>
      </nav>


    <!-- error and success messages -->
    {% with messages = get_flashed_messages(with_categories=True) %}
        {% if messages %}
            {% for category, message in messages %}
                {% if category == "error" %}
                <div class="alert alert-danger alter-dismissible fade show" style="margin-top: 0px" role="alert">  <!-- style these alert divs so that when the button is pressed they disappear-->
                    {{ message }}
                    <button type="button" class="btn-close" data-bs-dismiss="alert">X</button> 
                </div>
                {% else %}
                <div class="alert alert-success alter-dismissable fade show" style="margin-top: 0px" role="alert"> <!-- style these alert divs so that when the button is pressed they disappear-->
                    {{ message }}
                    <button type="button" class="btn-close" data-bs-dismiss="alert">X</button>
                </div>
                {% endif %}
            {% endfor %}
        {% endif %}
    {% endwith %}

    <div class="container">{% block content %}{% endblock %}</div>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
      crossorigin="anonymous"
    ></script>
    <script
      type="text/javascript"
      src="{{ url_for('static', filename='index.js')}}"
    ></script>
</body>
</html>

website/templates/create_post.html
{% extends "base.html" %} {% block title %}Home{% endblock %} 
{% block content%}
<h1 align="Center">Make a Post</h1>

<form method="POST">
    <label for="title">Title</label>
    <textarea name="title" id="title" placeholder="Post Title" class="form-control"></textarea>
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='signup.css') }}">

    <label for="text" >Text</label>
    <textarea name="text" id="text" placeholder="Add blog text here!" class="form-control" rows="10" cols="40"></textarea>
    
    <label for="tag1">Tags</label>
    <textarea name="tag1" id="tag1" placeholder="Tag 1 (required)" class="form-control" rows="1"></textarea>
    <br>
    <textarea name="tag2" id="tag2" placeholder="Tag 2 (required)" class="form-control" rows="1"></textarea>
    <br>
    <textarea name="tag3" id="tag3" placeholder="Tag 3 (required)" class="form-control" rows="1"></textarea>

    <input type="checkbox" name="is_private" id="is_private">
    <label for="is_private">Private?</label>
    <br>
    <div align="center">
    <button type="submit" class="create-btn">Post</button>
    </div>
</form>
<div align="center">
<a href="/home">
    <button type="button" class="back-btn">Back</button>
</a>
</div>


{% endblock %}

website/templates/home.html
{% extends "posts_div.html" %} 
{% block title %}Home{% endblock %} 

website/templates/login.html
{% extends "base.html" %}
{% block title %}Login{% endblock %}

{% block content%}
<form method="POST">
    
    <div class="form-group">
      <h3>Login</h3>
      <label for="email" class="login-label">Email Address</label>
      <input type="text" id="email" name="email" placeholder="Enter Email"/>
      <label for="password" class="login-label">Password</label>
      <input type="password" id="password" name="password" placeholder="Enter Password"/>

      <div>
        <button type="submit">Login</button>
      </div>
    </div>
  </form>
  {% endblock %}


  

website/templates/posts.html
{% extends "posts_div.html" %} 
{% block title %}{{username}}'s Posts{% endblock %} 

{% block header %}{{username}}'s posts{% endblock %}

{% block footer %} 
    <a href = "/home">
        <button type="button">Back</button>
    </a>
{% endblock %}

website/templates/posts_div.html


{% extends "base.html" %}
{% block title %}Home{% endblock %}
{% block content %}
  <h1>{% block header %}Posts{% endblock %}</h1>
  <div class="row" >
    {% for post in posts %}
      {% if post.is_private == 0 or user.id == post.author %}
        <div class="col-md-6"> <!-- Use Bootstrap's "col-md-6" class to create columns with 2 posts per row -->
          <div class="card mb-3" style="max-height: 300px; min-height:300px"> <!-- Use Bootstrap's "card" class to create a box for each post -->
            <div class="card-header justify-content-between">
              <h5 class="card-title">{{ post.title }}</h5>
              {% if user.id == post.author %}
                <a href="/delete-post/{{ post.id }}" class="card-link">Delete</a>
                <a href="/update-post/{{ post.id }}" class="card-link">Update</a> 
              {% endif %}
            </div>
              <div class="card-body">
              <a href="/posts/{{ post.user.username }}"><p class="card-subtitle mb-2 text-muted">{{ post.user.username }}:</p></a>
              <p class="card-text">{{ post.text }}</p>
              <p class="card-text">{{ post.date_created }}</p>
              <a href="/tag1/{{ post.tag1 }}" class="card-link">{{ post.tag1 }}</a>
              <a href="/tag2/{{ post.tag2 }}" class="card-link">{{ post.tag2 }}</a>
              <a href="/tag3/{{ post.tag3 }}" class="card-link">{{ post.tag3 }}</a>

            </div>
          </div>
        </div>
      {% endif %}
    {% endfor %}
  </div>
{% endblock %}

website/templates/signup.html
{% extends "base.html" %}
{% block title %}Sign Up{% endblock %}

{% block content %}
    <form method="POST">
      <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='signup.css') }}">
      
      <div class="form-group">
        <h3>Sign Up</h3>
        <label for="email" class="login-label">Email Address</label>
        <input type="text" id="email" name="email" placeholder="Enter Email"/>

        <label for="username" class="login-label">Username</label>
        <input type="text" id="username" name="username" class="form-control" placeholder="Enter Username"/>

        <label for="password1" class="login-label">Password</label>
        <input type="password" id="password1" name="password1" class="form-control" placeholder="Enter Password"/>

        <label for="password2" class="login-label">Password Again</label>
        <input type="password" id="password2" name="password2" class="form-control" placeholder="Enter Password Again"/>

        <div>
          <button type="submit">Sign Up</button>
        </div>
      </div>
    </form>
    {% endblock %}

website/templates/update_post.html
{% extends "base.html" %} {% block title %}Home{% endblock %} {% block content%}
<h1 align="center">Edit a Post</h1>

<form action="{{ url_for('views.update_post', id=post.id) }}", method="POST">

  <label for="title">Title</label>
  <textarea name="title" id="title" class="form-control">{{post.title}}</textarea>

  <label for="text">Text</label>
  <textarea name="text" id="text" class="form-control" rows="10" cols="40">{{post.text}}</textarea>
  <label for="tag1">Tags</label>
  <textarea name="tag1" id="tag1" class="form-control" placeholder="Tag 1 (required)" rows="1">{{ post.tag1 }}</textarea>
  <br>
  <textarea name="tag2" id="tag2" class="form-control" placeholder="Tag 2 (required)" rows="1">{{ post.tag2 }}</textarea>
  <br>
  <textarea name="tag3" id="tag3" class="form-control" placeholder="Tag 3 (required)" rows="1">{{ post.tag3 }}</textarea>

  {% if post.is_private == 0 %}
  <input type="checkbox" name="is_private" id="is_private">
  <label for="is_private">Private?</label>
  {% else %}
  <input type="checkbox" name="is_private" id="is_private" checked>
  <label for="is_private">Private?</label>
  {% endif %}
  
  <br>
  <div align="center">
    <button type="submit" class="update-btn">Update</button>
  </div>
</form>
<div align="center">
  <a href="/home"
    ><button type="button" class="back-btn">Back</button></a
  >
</div>
{% endblock %}